// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFlNblwMUfIJiX0wUcskam1H4NDlPwR3g',
    appId: '1:355847621686:web:80e0acd5e3ba4595e11c97',
    messagingSenderId: '355847621686',
    projectId: 'rinnape-489bc',
    authDomain: 'rinnape-489bc.firebaseapp.com',
    storageBucket: 'rinnape-489bc.appspot.com',
    measurementId: 'G-MQPW5M1GY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDstInf92lo5kQjXyJr5L1Qi1jBDcvLhwU',
    appId: '1:355847621686:android:e472c0e14857f8c0e11c97',
    messagingSenderId: '355847621686',
    projectId: 'rinnape-489bc',
    storageBucket: 'rinnape-489bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfhreEpqyVELHfZsHoYyTwCKy3GwIfpQM',
    appId: '1:355847621686:ios:2cc0490c62167c31e11c97',
    messagingSenderId: '355847621686',
    projectId: 'rinnape-489bc',
    storageBucket: 'rinnape-489bc.appspot.com',
    iosBundleId: 'com.example.psycho',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfhreEpqyVELHfZsHoYyTwCKy3GwIfpQM',
    appId: '1:355847621686:ios:6092f06b5c0ce2e8e11c97',
    messagingSenderId: '355847621686',
    projectId: 'rinnape-489bc',
    storageBucket: 'rinnape-489bc.appspot.com',
    iosBundleId: 'com.example.psycho.RunnerTests',
  );
}
